### ISSUE TITLE
Encoding issue?

### ISSUE THREAD

**Issue by octylFractal** [Nyr/reddit-email-notifications#1]
Not sure why, but the wget line has a strange character between `--` and `no-check-certificate`. Retyping the whole `--no-check-certificate` fixes it.

**Comment by Nyr** [comment]
Which character? This must be in your side, there isn't any as far as I can see.
![captura de pantalla 2015-08-04 a las 16 37 14](https://cloud.githubusercontent.com/assets/739489/9063375/4e0b444c-3ac7-11e5-83e6-a4e439729fbb.png)

**Comment by octylFractal** [comment]
It seems to be the dash itself.

**Comment by Nyr** [comment]
You are right, one of them was `EN DASH` while it should be `HYPHEN-MINUS`. Fixed.
